name: Nutricion y Vida Activa
favicon: null
layout_spectrum: 0.0062956311739981174
typography_spectrum: 0.9718631191644818
title: Nutricion y Vida Activa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76be43'
    - '#2e2925'
    - '#80ff80'
    - '#00ff00'
    - '#ffff00'
  brandStrength: 0.0625
  lightness: 0.4701564807910472
  saturation: 0.35770510556176305
  rhythmicContrast: 0.3198427213355899
purpose: []
