name: Nutricion y Vida Activa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76762
title: Nutricion y Vida Activa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76be43'
    - '#2e2925'
    - '#80ff80'
    - '#00ff00'
    - '#ffff00'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
